services:
  postgres:
    image: postgres:14.9
    ports:
      - 5432:5432
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    # volumes:
    #   - ./docker-content/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    name: caserv_infrastructure
